[package]
name = "simple_dapp"
version = "0.1.0"
authors = ["thaodt <ardtimeit@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eng-wasm = "0.1"
eng-wasm-derive = "0.1"
rustc-hex = "1.0.0" # 2.0.1?
serde_derive = "1.0.84"
serde = "1.0.84"
chrono = { version = "0.4", features = ["serde"] }
ethereum-types = "0.6.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
overflow-checks = true # Think about this, it will increase size and performance but I think it might be crucial